### ISSUE TITLE
Bug report: ValueError Incorrect format used for image. Should be an url linking to an image, a base64 string, a local path, or a PIL image.

### ISSUE THREAD

**Issue by sunxin000** [mi92/reverse-image-rag#1]
When executing the 'run_sample_i2.py' script, an error arises during the processing of the inputs:
```inputs = processor(text=prompt, images=[query_image, screenshot_image], return_tensors="pt")```
The error message indicates: ValueError: Incorrect format used for image. It should be an URL, a base64 string, a local path, or a PIL image. Upon debugging, I discovered that `screenshot_image` is `None`, which likely triggers the error. I configured the environment using the `setup_env.sh` script.

**Comment by sunxin000** [comment]
I believe there is a minor issue with the code. The function `load_image_wrapper` should not return `None`, as this would cause the subsequent line:
```inputs = processor(text=prompt, images=[query_image, screenshot_image], return_tensors="pt")```
to inevitably raise an error. This is because the `idefics2_processor` lacks a mechanism to handle `None` values.

**Comment by sunxin000** [comment]
I've discovered the cause of the error: the anonymous GitHub website allows only 350 requests every 15 minutes. When this limit is exceeded, the requests return an HTTP code 429. Could you please provide the screenshot dataset via Google Drive or another cloud storage service? I would greatly appreciate it!

**Comment by liamjxu** [comment]
Hi Xin,

Thank you for reporting this bug! I really appreciate your interest and thoroughness. As you have identified, the issue was caused by the request rate limit to the anonymous repo, which is a legacy of our anonymous paper submission process. 

To address this issue, we have made another commit with the following modification:
- Changed the URLs from the anonymous repo to a new public GitHub repo.

This change should resolve the rate limit issue without requiring any additional actions on your end. If you pull from the latest `paper` branch and rerun `run_sample_i2.py`, it should not run into any rate limit problems.

If you prefer having the data locally, you can download from [this repo](https://github.com/liamjxu/rir_data), put them under `local_data/`, and specify the `--data_source` argument as `local`.

Thank you again for this detailed and helpful bug report. Let me know if you run into any other issues :)
